version: '3.8'
name: chinook
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: chinook
      POSTGRES_PASSWORD: chinook
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./ChinookDatabase/DataSources/Chinook_PostgreSql.sql:/docker-entrypoint-initdb.d/Chinook_PostgreSql.sql
